version: '2'
services:
  postgres:
    image: postgres:13
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: local_showmeplace_local
      POSTGRES_USER: localmind
      POSTGRES_DB: showmeplace
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
