[default]
    DATABASE_PORT = "5432"
    DATABASE_USER = "localmind"
    DATABASE_PASSWORD = "local_showmeplace_local"
    DATABASE_DB = "showmeplace"
    DATABASE_HOST = "localhost"
    DATABASE_ECHO_MODE = false

    S3_IMAGES_BUCKET = "showmeplace-s3-bucket"
    S3_PRESIGNED_URL_EXPIRATION = 43200 #12 hours
    S3_PLACE_IMAGE_FOLDER = "place_images/"
    S3_CATEGORY_IMAGE_FOLDER = "category_images/"
    S3_USER_IMAGE_FOLDER = "user_images/"

    ACCESS_SECRET_KEY = ""
    ACCESS_KEY_ID = ""
    AWS_UPLOADING = true

    CHECK_IN_DISTANCE_METERS = 100 # in meters

    SERVER_RELOAD_MODE = true

    SECRET_PLACE_NAME = "Secret place"
    SECRET_MARK = "secret"
    PLACE_DECAY_DURATION_HOURS = 24

    COGNITO_USER_POOL = "us-east-1_60d3tsON2" #prod
    COGNITO_CLIENT_ID = "76tv59cs60tbmklb67halcvcmm"

    MACHINE_NAME = "smp-production"

    LOGGING_LEVEL = "DEBUG"
    LOG_TO_CONSOLE = true
    LOG_TO_FILE = true
    LOG_TO_SENTRY = false
    JSON_LOGS = false

    STARTING_COINS = 250 # this is how many coins we give to users

[test]
    DATABASE_PORT = "5432"
    DATABASE_USER = "localmind"
    DATABASE_PASSWORD = "local_showmeplace_local"
    DATABASE_DB = "showmeplace-test"
    DATABASE_HOST = "localhost"
    DATABASE_ECHO_MODE = false


