[default]
    DATABASE_PORT = "5432"
    DATABASE_USER = "mastermind"
    DATABASE_PASSWORD = "master_hrinder"
    DATABASE_DB = "hrinder"
    DATABASE_HOST = "localhost"
    DATABASE_ECHO_MODE = false




