[default]
    DATABASE_PORT = "5432"
    DATABASE_USER = "localmind"
    DATABASE_PASSWORD = "local_showmeplace_local"
    DATABASE_DB = "showmeplace"
    DATABASE_HOST = "localhost"
    DATABASE_ECHO_MODE = false




