"""fixtures

Revision ID: 5b70d55e83e9
Revises: 99a9d7196b0c
Create Date: 2022-09-17 16:47:19.505570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from models.db_models import Category, ActionsEconomy

revision = '5b70d55e83e9'
down_revision = '99a9d7196b0c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.bulk_insert(
        Category,
        [
            {"name": "Food"},
            {"name": "Rest"},
            {"name": "Nature"},
            {"name": "Culture"},
            {"name": "Kids"},
            {"name": "Beauty"},
            {"name": "Sport"},
            {"name": "Creative activities"},
            {"name": "Nightlife"},
            {"name": "Pets"},
            # {"name": "Auto"}, # :'(
        ],
    )

    op.bulk_insert(
        ActionsEconomy,
        [
            {"name": "Visit a place", "change_type": "EARN", "change_amount": "10"},
            {"name": "Create a place", "change_type": "EARN", "change_amount": "25"},
            {"name": "Share a profile", "change_type": "EARN", "change_amount": "25"},
            {"name": "Share a place", "change_type": "EARN", "change_amount": "10"},
            {
                "name": "Have your place visited",
                "change_type": "EARN",
                "change_amount": "5",
            },
            {
                "name": "Have your secret place visited",
                "change_type": "EARN",
                "change_amount": "35",
            },
            {
                "name": "Have your secret place opened",
                "change_type": "EARN",
                "change_amount": "25",
            },
            {
                "name": "Open a secret place",
                "change_type": "SPEND",
                "change_amount": "500",
            },
            {
                "name": "Create first secret place",
                "change_type": "SPEND",
                "change_amount": "50",
            },
            {
                "name": "Create a new place of the same category",
                "change_type": "SPEND",
                "change_amount": "150",
            },
            {
                "name": "Create new secret place",
                "change_type": "SPEND",
                "change_amount": "1000",
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
