"""email subsystem

Revision ID: fa620649e330
Revises: dd3647d3a599
Create Date: 2022-09-26 23:49:53.944253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fa620649e330"
down_revision = "dd3647d3a599"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
