"""owner_id_added

Revision ID: f1877c93a201
Revises: 9558148f537f
Create Date: 2022-09-22 23:58:23.366663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f1877c93a201"
down_revision = "9558148f537f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("place", sa.Column("owner_id", sa.Integer(), nullable=False))
    op.create_index(op.f("ix_place_owner_id"), "place", ["owner_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_place_owner_id_user"),
        "place",
        "user",
        ["owner_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_place_owner_id_user"), "place", type_="foreignkey")
    op.drop_index(op.f("ix_place_owner_id"), table_name="place")
    op.drop_column("place", "owner_id")
    # ### end Alembic commands ###
