"""email subsystem mkIII

Revision ID: 6b53d309f7c2
Revises: 1cefbd184a38
Create Date: 2022-10-11 00:12:31.339030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6b53d309f7c2"
down_revision = "1cefbd184a38"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("active_email_address_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_user_active_email_address_id_email_address"),
        "user",
        "email_address",
        ["active_email_address_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_user_active_email_address_id_email_address"),
        "user",
        type_="foreignkey",
    )
    op.drop_column("user", "active_email_address_id")
    # ### end Alembic commands ###
