"""secret_place_fixes

Revision ID: 168117358b61
Revises: 6b53d309f7c2
Create Date: 2022-10-21 08:20:07.526513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '168117358b61'
down_revision = '6b53d309f7c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('secret_extra_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_place_secret_extra_id_secret_extras'), 'place', 'secret_extras', ['secret_extra_id'], ['id'], ondelete='CASCADE')
    op.drop_column('place', 'is_secret_place')
    op.drop_constraint('fk_secret_extras_place_id_place', 'secret_extras', type_='foreignkey')
    op.drop_column('secret_extras', 'place_id')
    op.drop_column('user', 'has_onboarded')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('has_onboarded', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('secret_extras', sa.Column('place_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_secret_extras_place_id_place', 'secret_extras', 'place', ['place_id'], ['id'], ondelete='CASCADE')
    op.add_column('place', sa.Column('is_secret_place', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_place_secret_extra_id_secret_extras'), 'place', type_='foreignkey')
    op.drop_column('place', 'secret_extra_id')
    # ### end Alembic commands ###
