"""place mark

Revision ID: dd3647d3a599
Revises: f1877c93a201
Create Date: 2022-09-24 16:24:23.045516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dd3647d3a599"
down_revision = "f1877c93a201"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("category", sa.Column("mark", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("category", "mark")
    # ### end Alembic commands ###
