"""fixtures and economy

Revision ID: 99a9d7196b0c
Revises: 16c000248278
Create Date: 2022-09-17 15:04:35.967472

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
from models.db_models import Category, ActionsEconomy

revision = "99a9d7196b0c"
down_revision = "16c000248278"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "actions_economy",
        sa.Column(
            "record_created",
            sa.DateTime(),
            server_default=sa.text("statement_timestamp()"),
            nullable=False,
        ),
        sa.Column(
            "record_modified",
            sa.DateTime(),
            server_default=sa.text("statement_timestamp()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("action_name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("change_type", sa.String(), nullable=False),
        sa.Column("change_amount", sa.Integer(), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_actions_economy")),
    )
    op.create_index(
        op.f("ix_actions_economy_record_modified"),
        "actions_economy",
        ["record_modified"],
        unique=False,
    )
    op.drop_index("ix_coins_economy_record_modified", table_name="coins_economy")
    op.drop_table("coins_economy")

    op.bulk_insert(
        Category,
        [
            {"name": "Food"},
            {"name": "Rest"},
            {"name": "Nature"},
            {"name": "Culture"},
            {"name": "Kids"},
            {"name": "Beauty"},
            {"name": "Sport"},
            {"name": "Creative activities"},
            {"name": "Nightlife"},
            {"name": "Pets"},
            # {"name": "Auto"}, # :'(
        ],
    )

    op.bulk_insert(
        ActionsEconomy,
        [
            {"name": "Visit a place", "change_type": "EARN", "change_amount": "10"},
            {"name": "Create a place", "change_type": "EARN", "change_amount": "25"},
            {"name": "Share a profile", "change_type": "EARN", "change_amount": "25"},
            {"name": "Share a place", "change_type": "EARN", "change_amount": "10"},
            {
                "name": "Have your place visited",
                "change_type": "EARN",
                "change_amount": "5",
            },
            {
                "name": "Have your secret place visited",
                "change_type": "EARN",
                "change_amount": "35",
            },
            {
                "name": "Have your secret place opened",
                "change_type": "EARN",
                "change_amount": "25",
            },
            {
                "name": "Open a secret place",
                "change_type": "SPEND",
                "change_amount": "500",
            },
            {
                "name": "Create first secret place",
                "change_type": "SPEND",
                "change_amount": "50",
            },
            {
                "name": "Create a new place of the same category",
                "change_type": "SPEND",
                "change_amount": "150",
            },
            {
                "name": "Create new secret place",
                "change_type": "SPEND",
                "change_amount": "1000",
            },
        ],
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "coins_economy",
        sa.Column(
            "record_created",
            postgresql.TIMESTAMP(),
            server_default=sa.text("statement_timestamp()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "record_modified",
            postgresql.TIMESTAMP(),
            server_default=sa.text("statement_timestamp()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("change_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("change_amount", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_coins_economy"),
    )
    op.create_index(
        "ix_coins_economy_record_modified",
        "coins_economy",
        ["record_modified"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_actions_economy_record_modified"), table_name="actions_economy"
    )
    op.drop_table("actions_economy")
    # ### end Alembic commands ###
