"""external_id_and_economy

Revision ID: 0521b017e695
Revises: 52c193cebeb6
Create Date: 2022-09-16 08:45:28.514513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0521b017e695"
down_revision = "52c193cebeb6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "coins_economy",
        sa.Column(
            "record_created",
            sa.DateTime(),
            server_default=sa.text("statement_timestamp()"),
            nullable=False,
        ),
        sa.Column(
            "record_modified",
            sa.DateTime(),
            server_default=sa.text("statement_timestamp()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("change_type", sa.String(), nullable=False),
        sa.Column("change_amount", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coins_economy")),
    )
    op.create_index(
        op.f("ix_coins_economy_record_modified"),
        "coins_economy",
        ["record_modified"],
        unique=False,
    )

    op.alter_column(
        "user", "cognito_user_id", nullable=False, new_column_name="external_id", type_=sa.Text()
    )
    op.add_column(
        "user",
        sa.Column(
            "external_id_type", type_=sa.Text(), server_default="COGNITO", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "external_id", nullable=False, new_column_name="cognito_user_id", type_=sa.String()
    )
    op.drop_column("user", "external_id_type")
    op.drop_index(op.f("ix_coins_economy_record_modified"), table_name="coins_economy")
    op.drop_table("coins_economy")
    # ### end Alembic commands ###
