"""empty message

Revision ID: 3a52a125571f
Revises: 
Create Date: 2022-08-30 23:10:20.116966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a52a125571f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_place_category'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('has_onboarded', sa.Boolean(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('coins', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_table('place',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('coordinate_longitude', sa.Float(), nullable=False),
    sa.Column('coordinate_latitude', sa.Float(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['place_category.id'], name=op.f('fk_place_category_id_place_category'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_place'))
    )
    op.create_index(op.f('ix_place_category_id'), 'place', ['category_id'], unique=False)
    op.create_table('m2m_user_place_favourite',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], name=op.f('fk_m2m_user_place_favourite_place_id_place'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_m2m_user_place_favourite_user_id_user'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'place_id', name='m2m_user_place_favourite_pkey')
    )
    op.create_table('m2m_user_place_ownership',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], name=op.f('fk_m2m_user_place_ownership_place_id_place'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_m2m_user_place_ownership_user_id_user'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'place_id', name='m2m_user_place_ownership_pkey')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('m2m_user_place_ownership')
    op.drop_table('m2m_user_place_favourite')
    op.drop_index(op.f('ix_place_category_id'), table_name='place')
    op.drop_table('place')
    op.drop_table('user')
    op.drop_table('place_category')
    # ### end Alembic commands ###
