"""crucial fixtures

Revision ID: f3c89d81106a
Revises: 0521b017e695
Create Date: 2022-09-17 07:01:42.104228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from models.db_models import Category

revision = 'f3c89d81106a'
down_revision = '0521b017e695'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.bulk_insert(Category,
                   [
                       {"name": "Food"},
                       {"name": "Party"},
                       {"name": "Shopping"},
                       {"name": "Auto"},
                       {"name": "Shopping"},
                       {"name": "Shopping"},
                       {"name": "Shopping"},
                   ]
                   )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
